name: cs

on:
  repository_dispatch:
#  release:
#    types: published
#  push:
#    branches:
#      - master
#    paths:
#      - 'n1稳定版.config'
#  schedule:
#    - cron: 0 21 * * *
  watch:
    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: n1稳定版.config
  DIY_SH: n1稳定版.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_WETRANSFER: false
  UPLOAD_COWTRANSFER: false
  TZ: Asia/Shanghai
  FILE_NAME: n1稳定版

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:     
    - name: Checkout
      uses: actions/checkout@master
 
    - name: Clone source code # 克隆的源代码
      id: openwrt
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        
    - name: Build firmware
      run: |
        wget https://github.com/bin20088/Bin/releases/download/n1稳定版/openwrt-bcm27xx-bcm2710-rpi-3-rootfs.tar.gz
        git clone https://github.com/tuanqing/mknop.git
        cp *.tar.gz ./mknop/openwrt/123.rootfs.tar.gz
        sudo ./mknop/make -d
        cd mknop/out
        echo "::set-env name=FIRMWARE::$PWD"

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: cs
        path: ${{ env.FIRMWARE }}
